var Begin=Class.extend({
    init:function(ob){
        this.image1=ob.R["help"];
        this.image2=ob.R["taiji"];
        this.image3=ob.R["zhihei"];
        this.image4=ob.R["zhibai"];
        this.image5=ob.R["title"];
        this.rotate=0;
        this.y1=220;
        this.y2=420;
        this.y3=50;
        this.y5=0;
        ob.scene.actors.push(this);
    },
    update:function(){
        this.rotate+=0.007;
        //场景2 时的退场动画
        if(game.scene.scenenum==2){
            this.y1-=7;
            this.y2-=7;
            this.y3-=7;
            this.y5-=7;
        }
        if(this.y2<-200){
            this.godie();
        }
    },
    render:function(){
        //旋转的太极
        game.ctx.save();
        game.ctx.translate(399,this.y1);
        game.ctx.rotate(this.rotate);
        game.ctx.drawImage(this.image2,-175,-175,350,350);
        game.ctx.restore();
        //先后手选择
        game.ctx.drawImage(this.image3,200,this.y2,150,100);
        game.ctx.drawImage(this.image4,450,this.y2,150,100);
        //规则说明
        game.ctx.drawImage(this.image1,588,this.y3,150,45);
        //标题
        game.ctx.drawImage(this.image5,0,this.y5);
    },
    godie:function(){
            game.scene.actors=_.without(game.scene.actors,this);
        }
})